url: "https://www.danxiang.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Daniel Xiang" # the name of your site, e.g. ACME Corp.
description: ""
